.PHONY: clean All

All:
	@echo "----------Building project:[ week 1 - Debug ]----------"
	@"$(MAKE)" -f  "week 1.mk"
clean:
	@echo "----------Cleaning project:[ week 1 - Debug ]----------"
	@"$(MAKE)" -f  "week 1.mk" clean
